# Generated by Django 4.1.7 on 2023-03-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "size",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=1,
                    ),
                ),
                ("color", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Hats", "Hats"),
                            ("Jacket", "Jacket"),
                            ("Trousers", "Trousers"),
                            ("Shoes", "Shoes"),
                            ("Sweatshirt", "Sweatshirt"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
