# Generated by Django 4.1.7 on 2023-03-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(upload_to="product_pics"),
        ),
    ]
